source 'https://rubygems.org'

ruby '2.1.1'


gem 'rails', '4.1.5'

gem 'pg'

gem 'jquery-rails'

gem 'turbolinks'



group :assets do
	gem 'sass-rails'
	gem 'uglifier'
	gem 'coffee-rails'
end

group :development do
	gem 'rails_db_info'
end


group :test, :development do
  gem 'rspec-rails'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry'
  gem 'faker'
end

group :test do 
	gem 'shoulda-matchers'
	gem 'debugger'
	gem 'capybara'
	gem 'factory_girl_rails'
end



