# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5363ed42758baedee591f17f6b5e307b0ef3785310580aec7bd44363d798bc5d70d2073add71b1821d7b2bc7cfb0fe51c327e8c59735cc16847cabc4c24e750d

test:
  secret_key_base: 8a209d9961c572c37d45f1632f65c581d541d45619c362d38eec26c3e17e8a18da6b910df0bf6360ef082d75dd0d8cefc8c610e0521ded81155715bb4ba0fb2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
